openapi: 3.0.4
info:
  title: Text Summarizer
  description: Text Summarizer is a simple tool for summarizing text. It returns a summary of the text.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/textsummarizer:
    post:
      summary: Summarize Text
      description: Text Summarizer is a simple tool for summarizing text. It returns a summary of the text.
      operationId: textsummarizer
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  originalWords: 67
                  summaryWords: 30
                  percentDifference: 44.78
                  summary: A news article can include accounts of eyewitnesses to the happening event. Headlines can be used to focus the reader's attention on a particular (or main) part of the article.
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to summarize (up to 5000 characters)
                  example: A news article can include accounts of eyewitnesses to the happening event. It can contain photographs, accounts, statistics, graphs, recollections, interviews, polls, debates on the topic, etc. Headlines can be used to focus the reader's attention on a particular (or main) part of the article. The writer can also give facts and detailed information following answers to general questions like who, what, when, where, why and how.
                sentences:
                  type: integer
                  description: The length of the summary (number of sentences)
                  default: '3'
                  example: 2
              required:
              - text
              example:
                text: A news article can include accounts of eyewitnesses to the happening event. It can contain photographs, accounts, statistics, graphs, recollections, interviews, polls, debates on the topic, etc. Headlines can be used to focus the reader's attention on a particular (or main) part of the article. The writer can also give facts and detailed information following answers to general questions like who, what, when, where, why and how.
                sentences: 2
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
